services:
  - type: web
    name: lawbridge-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/your-org/lawbridge-backend
    branch: main
    envVars:
      - key: MONGO_URI
        value: <your-MongoDB-Atlas-connection-string>
      - key: JWT_SECRET
        value: <secure-jwt-secret>
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health